name: cli_generator
description: for generating code
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"


executables:
  cli_generate:

dependencies:
  path: ^1.9.0
  rename: ^2.1.1
  args: ^2.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


